annotations:
  helm.sh/images: |-
    - image: ghcr.io/leooamaral/suse-ai-operator:0.2.0-dev.1
      name: suse-ai-operator
  license: Apache-2.0
apiVersion: v2
name: suse-ai-operator
version: 0.2.0-dev.1
description: SUSE AI Operator
type: application
home: https://github.com/SUSE/suse-ai-operator
icon: https://github.com/SUSE/suse-ai-lifecycle-manager/blob/main/pkg/suse-ai-lifecycle-manager/assets/logo.svg
sources:
  - https://github.com/SUSE/suse-ai-operator
appVersion: 0.2.0-dev.1
maintainers:
  - url: https://www.suse.com/
    name: SUSE LLC
keywords:
  - rancher
  - extension
  - ai
  - kubernetes
  - operator
