{{- if .Values.rbacHelpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: suse-ai-operator
    name: suse-ai-operator-installaiextension-viewer-role
rules:
    - apiGroups:
        - ai-platform.suse.com
      resources:
        - installaiextensions
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - ai-platform.suse.com
      resources:
        - installaiextensions/status
      verbs:
        - get
{{- end }}
