apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: suse-ai-operator
    name: suse-ai-operator-leader-election-rolebinding
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: suse-ai-operator-leader-election-role
subjects:
    - kind: ServiceAccount
      name: suse-ai-operator-controller-manager
      namespace: {{ .Release.Namespace }}
