apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: suse-ai-operator
    name: suse-ai-operator-manager-rolebinding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: suse-ai-operator-manager-role
subjects:
    - kind: ServiceAccount
      name: suse-ai-operator-controller-manager
      namespace: {{ .Release.Namespace }}
