apiVersion: ai-platform.suse.com/v1alpha1
kind: InstallAIExtension
metadata:
  labels:
    app.kubernetes.io/name: suse-ai-operator
    app.kubernetes.io/managed-by: kustomize
  name: suseai
spec:
  helm:
    name: suse-ai-lifecycle-manager
    url: "ghcr.io/suse/chart/suse-ai-lifecycle-manager"
    version: "1.0.0"
    type: "oci"
  extension:
    name: suse-ai-lifecycle-manager
    version: "1.0.0"
