name: Build and Publish Extension [Container and Helm Chart - Multi-Arch]

on: [push, pull_request, workflow_dispatch]

env:
  CHART_PATH: charts/suse-ai-lifecycle-manager
  CHART_REGISTRY: oci://ghcr.io/leooamaral/chart
  IMAGE_NAME: ghcr.io/leooamaral/suse-ai-lifecycle-manager

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.tags.outputs.TAGS }}
    steps:
      - name: Calculate tags
        id: tags 
        shell: bash
        run: |
          echo "TAGS<<##" >> "$GITHUB_OUTPUT"
          ref=${{ github.ref }}
          case "$ref" in
            refs/heads/main)
              echo "latest" >> "$GITHUB_OUTPUT";;
            refs/tags/*)
              echo "${ref#refs/tags/}" >> "$GITHUB_OUTPUT";;
            *)
              echo "${{ github.sha }}" >> "$GITHUB_OUTPUT";;
          esac
          echo "##" >> "$GITHUB_OUTPUT"

  build-amd64:
    name: Build Container Image and Helm Chart - amd64
    runs-on: ubuntu-24.04
    needs: prepare
    env:
      RELEASE_TAG: ${{ needs.prepare.outputs.release_tag }}
    permissions:
      contents: read
      packages: write
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: yarn

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Parse Extension Name
        if: ${{ github.event_name == 'push' && startsWith(github.ref_name, 'suse-ai-lifecycle-manager-') }}
        id: parsed-name
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          yarn parse-tag-name ${{ env.RELEASE_TAG }} ${{ github.run_id }} "catalog"

      - name: Build and push UI image
        if: ${{ github.event_name == 'push' && startsWith(github.ref_name, 'suse-ai-lifecycle-manager-') }}
        run: |
          yarn publish-pkgs -c -i '' -r ghcr.io -o 'leooamaral' -t "${{ env.RELEASE_TAG }}"

      - name: Tag amd64
        if: ${{ github.event_name == 'push' && startsWith(github.ref_name, 'suse-ai-lifecycle-manager-') }}
        run: |
          # VERSION=$(echo "${{ env.RELEASE_TAG }}" | sed 's/^.*-//')
          VERSION=${RELEASE_TAG##*-}
          docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:$VERSION-amd64
          docker push $IMAGE_NAME:$VERSION-amd64

  build-arm64:
    name: Build Container Image and Helm Chart - arm64
    runs-on: ubuntu-24.04-arm
    needs: prepare
    env:
      RELEASE_TAG: ${{ needs.prepare.outputs.release_tag }}
    permissions:
      contents: read
      packages: write
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: yarn

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Parse Extension Name
        if: ${{ github.event_name == 'push' && startsWith(github.ref_name, 'suse-ai-lifecycle-manager-') }}
        id: parsed-name
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          yarn parse-tag-name ${{ env.RELEASE_TAG }} ${{ github.run_id }} "catalog"

      - name: Build and push UI image
        if: ${{ github.event_name == 'push' && startsWith(github.ref_name, 'suse-ai-lifecycle-manager-') }}
        run: |
          yarn publish-pkgs -c -i '' -r ghcr.io -o 'leooamaral' -t "${{ env.RELEASE_TAG }}"

      - name: Tag arm64
        if: ${{ github.event_name == 'push' && startsWith(github.ref_name, 'suse-ai-lifecycle-manager-') }}
        run: |
          # VERSION=$(echo "${{ env.RELEASE_TAG }}" | sed 's/^.*-//')
          VERSION=${RELEASE_TAG##*-}
          docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:$VERSION-arm64
          docker push $IMAGE_NAME:$VERSION-arm64

  manifest:
    needs: [prepare, build-amd64, build-arm64]
    env:
      RELEASE_TAG: ${{ needs.prepare.outputs.release_tag }}
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && startsWith(github.ref_name, 'suse-ai-lifecycle-manager-') }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
    
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create multi-arch manifest
        run: |
          # VERSION=$(echo "${{ env.RELEASE_TAG }}" | sed 's/^.*-//')
          VERSION=${RELEASE_TAG##*-}
      
          docker buildx imagetools create \
            -t $IMAGE_NAME:$VERSION \
            $IMAGE_NAME:$VERSION-amd64 \
            $IMAGE_NAME:$VERSION-arm64

      - name: Package Helm Chart
        id: package
        run: |
          chart_package=$(helm package $CHART_PATH --destination . | awk '{print $NF}')
          echo "chart_package=$chart_package" >> $GITHUB_OUTPUT

      - name: Publish Helm Chart
        run: |
          helm push ${{ steps.package.outputs.chart_package }} \
            $CHART_REGISTRY
